Aula 03 - platini

In [4]:
import pandas as pd

In [43]:
#df de dataframe/ fazendo a leitura do arquivo.
df = pd.read_csv(r"data\dataset_aula1_numpy_pandas.csv")

In [44]:
df.head(5)

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [45]:
df.tail(5)

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [46]:
#40 linhas e 6 colunas
df.shape

(40, 6)

In [47]:
#tras a metrica geral dos Dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     object
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), object(1)
memory usage: 2.0+ KB

In [48]:
#procura valores nulos e soma
df.isna().sum

<bound method DataFrame.sum of     id_registro  setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0         False  False          False          False         False  False
1         False  False          False          False         False  False
2         False  False          False          False         False  False
3         False  False          False          False         False  False
4         False  False          False          False         False  False
5         False  False          False          False         False  False
6         False  False          False          False         False  False
7         False  False          False          False         False  False
8         False  False          False          False         False  False
9         False  False          False          False         False  False
10        False  False          False          False         False  False
11        False  False          False          False         False  False
12        False  False          False          False         False  False
13        False  False          False          False         False  False
14        False  False          False          False         False  False
15        False  False          False          False         False  False
16        False  False          False          False         False  False
17        False  False          False          False         False  False
18        False  False          False          False         False  False
19        False  False          False          False         False  False
20        False  False          False          False         False  False
21        False  False          False          False         False  False
22        False  False          False          False         False  False
23        False  False          False          False         False  False
24        False  False          False          False         False  False
25        False  False          False          False         False  False
26        False  False          False          False         False  False
27        False  False          False          False         False  False
28        False  False          False          False         False  False
29        False  False          False          False         False  False
30        False  False          False          False         False  False
31        False  False          False          False         False  False
32        False  False          False          False         False  False
33        False  False          False          False         False  False
34        False  False          False          False         False  False
35        False  False          False          False         False  False
36        False  False          False          False         False  False
37        False  False          False          False         False  False
38        False  False          False          False         False  False
39        False  False          False          False         False  False>

In [49]:
df.isna()

    id_registro  setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0         False  False          False          False         False  False
1         False  False          False          False         False  False
2         False  False          False          False         False  False
3         False  False          False          False         False  False
4         False  False          False          False         False  False
5         False  False          False          False         False  False
6         False  False          False          False         False  False
7         False  False          False          False         False  False
8         False  False          False          False         False  False
9         False  False          False          False         False  False
10        False  False          False          False         False  False
11        False  False          False          False         False  False
12        False  False          False          False         False  False
13        False  False          False          False         False  False
14        False  False          False          False         False  False
15        False  False          False          False         False  False
16        False  False          False          False         False  False
17        False  False          False          False         False  False
18        False  False          False          False         False  False
19        False  False          False          False         False  False
20        False  False          False          False         False  False
21        False  False          False          False         False  False
22        False  False          False          False         False  False
23        False  False          False          False         False  False
24        False  False          False          False         False  False
25        False  False          False          False         False  False
26        False  False          False          False         False  False
27        False  False          False          False         False  False
28        False  False          False          False         False  False
29        False  False          False          False         False  False
30        False  False          False          False         False  False
31        False  False          False          False         False  False
32        False  False          False          False         False  False
33        False  False          False          False         False  False
34        False  False          False          False         False  False
35        False  False          False          False         False  False
36        False  False          False          False         False  False
37        False  False          False          False         False  False
38        False  False          False          False         False  False
39        False  False          False          False         False  False

In [50]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [51]:
df[["temperatura_c", "setor"]]

    temperatura_c     setor
0           72.62  Montagem
1           81.65  Usinagem
2           68.87  Usinagem
3           66.84  Usinagem
4           66.23  Usinagem
5           64.79  Usinagem
6           85.02  Usinagem
7           60.31  Inspeção
8           75.84  Montagem
9           68.38  Inspeção
10          76.31  Usinagem
11          74.79  Inspeção
12          76.31  Usinagem
13          63.28  Montagem
14          64.98  Montagem
15          81.48  Montagem
16          79.62  Montagem
17          69.80  Inspeção
18          77.16  Inspeção
19          73.30  Usinagem
20          79.77  Inspeção
21          71.76  Usinagem
22          74.16  Inspeção
23          74.69  Usinagem
24          74.03  Usinagem
25          75.96  Usinagem
26          60.80  Usinagem
27          69.37  Montagem
28          70.28  Montagem
29          73.53  Inspeção
30          63.59  Montagem
31          68.91  Inspeção
32          77.62  Inspeção
33          73.32  Inspeção
34          78.24  Usinagem
35          68.47  Usinagem
36          75.62  Inspeção
37          78.50  Usinagem
38          76.19  Montagem
39          68.64  Montagem

In [52]:
#comando para visualizar as colunas em forma de lista
df.columns.to_list()

['id_registro',
 'setor',
 'temperatura_c',
 'tempo_ciclo_s',
 'producao_dia',
 'falha']

## Exercício

-Importem a biblioteca Pandas 
-realizar a leitura dos dados
-exibir a quantidade de linnhas e colunas
-exibir as informaçoes gerais dessa base de dados
-Realizar a contagem de valores não nulos
-Exibir os nomes das colunas
-exibir a descrição( min, max, meanx std, quartis)

In [3]:
#lendo o Arquivo :)
df = pd.read_csv(r"data\dataset_aula01_techshop_vendas (1).csv")

In [54]:
#mostra os dados

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    object
 1   categoria        800 non-null    object
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    object
 5   canal_marketing  800 non-null    object
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 43.9+ KB

In [55]:
#os 5 primeiros
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [56]:
#os 5 ultimos
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [ ]:
#Quantidade de Linhas, colunas
df.shape

(800, 7)

In [57]:
df.notnull().sum()

data_pedido        800
categoria          800
preco_unitario     800
quantidade         800
regiao             800
canal_marketing    800
avaliacao          800
dtype: int64

In [20]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [ ]:
#quais sao nulos
df.isna

<bound method DataFrame.isna of     data_pedido    categoria  preco_unitario  quantidade    regiao  \
0    2024-01-01   Acessórios           36.20           1   Sudeste
1    2024-01-01   Acessórios          122.61           5   Sudeste
2    2024-01-02   Acessórios          151.19           4       Sul
3    2024-01-03          TVs         3399.16           2   Sudeste
4    2024-01-04  Smartphones         3180.94           2  Nordeste
..          ...          ...             ...         ...       ...
795  2024-12-27        Áudio         1128.44           4       Sul
796  2024-12-27   Acessórios          209.29           4   Sudeste
797  2024-12-28    Notebooks         7979.84           2   Sudeste
798  2024-12-28    Notebooks         4168.01           1  Nordeste
799  2024-12-28   Acessórios          111.95           1       Sul

    canal_marketing  avaliacao
0         Instagram        3.3
1          Orgânico        4.4
2        Google Ads        4.6
3        Google Ads        4.1
4         Instagram        3.9
..              ...        ...
795        Orgânico        4.6
796      Google Ads        3.8
797      Google Ads        4.4
798       Instagram        4.1
799      Google Ads        4.7

[800 rows x 7 columns]>

In [ ]:
#quantos são nulos
df.isna().sum()

data_pedido        0
categoria          0
preco_unitario     0
quantidade         0
regiao             0
canal_marketing    0
avaliacao          0
dtype: int64

In [ ]:
#Colunas nomes
df.columns.to_list()

['data_pedido',
 'categoria',
 'preco_unitario',
 'quantidade',
 'regiao',
 'canal_marketing',
 'avaliacao']

Aula 04

In [7]:
df["faturamento"] = df["preco_unitario"] * df ["quantidade"]
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88

In [5]:
df = pd.read_csv(r"data\dataset_aula01_techshop_vendas (1).csv",
parse_dates =["data_pedido"])

In [ ]:
#por causa da celula anterior agora é um datetime64[ns] e antes era um strg
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    datetime64[ns]
 1   categoria        800 non-null    object
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    object
 5   canal_marketing  800 non-null    object
 6   avaliacao        800 non-null    float64
 7   faturamento      800 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 50.1+ KB

In [6]:
df.tratado = df.copy()

C:\Users\FIC\AppData\Local\Temp\ipykernel_31076\2592890084.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.tratado = df.copy()